# Replace with location of your wallpaper
$wallpaper = /home/yorye/img/wallpaper/1.png

preload = $wallpaper
# Asignar el mismo fondo de pantalla a cada monitor
wallpaper = eDP-1,$wallpaper
wallpaper = DVI-I-1, $wallpaper
wallpaper = DVI-I-2, $wallpaper

# Opciones avanzadas (si son compatibles)
splash = true
splash_offset = 10
ipc = off


splash = false

ipc = on
