# Cargar tema personalizado
include theme.conf

# Fuente
font_family      JetbrainsMono Nerd Font
font_size        12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

# Configuración del cursor
cursor            #ebdbb2
cursor_text_color #282828

# Transparencia (debes usar un compositor como picom)
background_opacity 0.90
background_image none

# Scrollback
scrollback_lines 10000

# Definir cómo se comporta la ventana
window_padding_width 5
window_padding_height 5

# Aumentar rendimiento
max_fps 60

# Activar el borde del terminal
window_border_width 1
window_border_color #a89984

# Colores de selección
selection_background #3c3836
selection_foreground #fbf1c7

# Resto de configuraciones visuales
enable_audio_bell no
bell_on_tab true

