# Tamaño de fuente y familia
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Colores Gruvbox Light
foreground       #3c3836
background       #fbf1c7
selection_foreground #fbf1c7
selection_background #3c3836

# Colores ANSI
color0  #fbf1c7
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #7c6f64

color8  #928374
color9  #9d0006
color10 #79740e
color11 #b57614
color12 #076678
color13 #8f3f71
color14 #427b58
color15 #3c3836

# Cursor
cursor          #3c3836
cursor_text_color #fbf1c7

# Comportamiento
scrollback_lines 10000
enable_audio_bell no
bell_on_tab true

# Ventanas
window_padding_width 5

