  ___        _            _             _   
 / _ \      | |          | |           | |  
/ /_\ \_   _| |_ ___  ___| |_ __ _ _ __| |_ 
|  _  | | | | __/ _ \/ __| __/ _` | '__| __|
| | | | |_| | || (_) \__ \ || (_| | |  | |_ 
\_| |_/\__,_|\__\___/|___/\__\__,_|_|   \__|
                                            
exec-once = waybar & hyprpaper
# exec-once = swaync -s ~/.config/dotfiles/swaync/style.css -c ~/.config/dotfiles/swaync/config.json
# exec-once = [workspace 3 silent] $discord
# exec-once = [workspace 4 silent] $whatsapp
# exec-once = [workspace 4 silent] $telegram
