___  ___            _ _                 
|  \/  |           (_) |                
| .  . | ___  _ __  _| |_ ___  _ __ ___ 
| |\/| |/ _ \| '_ \| | __/ _ \| '__/ __|
| |  | | (_) | | | | | || (_) | |  \__ \
\_|  |_/\___/|_| |_|_|\__\___/|_|  |___/

monitor = eDP-1,    1920x1080@60,  2560x0, 1 # Portatil
monitor = DVI-I-1,  2560x1440@144, 0x0, 1 # LG principal
monitor = DVI-I-2,  2560x1440@144, -1440x0, 1, transform, 1 # LG secundaria
