#  _    _            _                             
# | |  | |          | |                            
# | |  | | ___  _ __| | _____ _ __   __ _  ___ ___ 
# | |/\| |/ _ \| '__| |/ / __| '_ \ / _` |/ __/ _ \
# \  /\  / (_) | |  |   <\__ \ |_) | (_| | (_|  __/
#  \/  \/ \___/|_|  |_|\_\___/ .__/ \__,_|\___\___|
#                            | |                   
#                            |_|                   

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P i>
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}
#Waorkspace Rules Customised accordingly
# workspace=special:overveiw,gapsout:80
# workspace=1,gapsout:0,gapsin:0,bordersize:0
# workspace=3,gapsout:50,bordersize:3
# workspace=4,gapsout:50
# workspace=2,bordersize:4,gapsout:20,gapsin:5
# workspace=special:running,rounding:false,gapsout:80
